export const NUM_SLOTS_IN_LARGER_DIMENSION = 21;
export const SLOT_WIDTH_PERCENTAGE = 100 / NUM_SLOTS_IN_LARGER_DIMENSION;
export const PLAYER_SIZE_IN_SLOTS = 2;
export const PLAYER_SIZE_PERCENT =
  (PLAYER_SIZE_IN_SLOTS * 100) / NUM_SLOTS_IN_LARGER_DIMENSION;
export const BASE_SLOTS_MOVED_PER_SECOND = 2.5;
export const BONUS_SLOTS_MOVED_PER_SECOND_WITH_MOUTH_MOVEMENT = 3.5;
export const SLOTS_MOVED_PER_MOUTH_MOVE = 1;
