export const PLAYFIELD_SIZE = 100;
export const PLAYER_SIZE = 12;
export const PLAYER_SPEED_PER_SECOND = PLAYFIELD_SIZE / 2;
export const SECONDS_OF_MOVEMENT_PER_MOUTH_MOVE = 0.225;
export const NUM_PELLETS = 7;
export const TOTAL_SLOTS = NUM_PELLETS * 2 + 1;
export const SLOT_WIDTH = PLAYFIELD_SIZE / TOTAL_SLOTS;
